# Generated by Django 5.2.4 on 2025-07-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier_app", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PICKED", "Picked"),
                    ("IN_TRANSIT", "In Transit"),
                    ("RETURNED", "Returned"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETE", "Complete"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
