# Generated by Django 5.2.4 on 2025-07-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier_app", "0003_order_is_paid_order_stripe_payment_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'card', 'cash', 'stripe'",
                max_length=50,
                null=True,
            ),
        ),
    ]
