# Generated by Django 5.2.4 on 2025-07-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier_app", "0004_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
    ]
