# Generated by Django 5.2.4 on 2025-07-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier_app", "0005_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
